const typeMap = {
  All: "All",
  "Amusement Park": "amusement_park",
  Aquarium: "aquarium",
  "Art Gallery": "art_gallery",
  Church: "church",
  Museum: "museum",
  Park: "park",
  Zoo: "zoo",
  Stadium: "stadium",
  "Movie Theater": "movie_theater",
  Casino: "casino",
  "Night Club": "night_club",
  Restaurant: "restaurant",
  Bar: "bar",
  Cafe: "cafe",
  Bakery: "bakery",
  Lodging: "lodging",
  Hotel: "hotel",
  "Shopping Mall": "shopping_mall",
  Library: "library",
  "City Hall": "city_hall",
  Other: "Other",
};

export default typeMap;
